# Generated by Django 4.0.6 on 2022-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombreapp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='regressiontest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadRT', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='unittest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.IntegerField()),
                ('cantidadUT', models.IntegerField()),
            ],
        ),
    ]
